name: Check PR size

on: pull_request

    
env:
  # Run all cargo commands with --verbose.
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"
  TEST_STARTUP_INTERVAL: "40"

jobs:
  check_pr_size:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Check PR size doesn't break set limit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: maidsafe/pr_size_checker@v2
      with:
        max_lines_changed: 200